"""
CTIR Adapter — OpenIOC 1.1 XML
Produces OpenIOC XML documents consumable by IPA and legacy SIEMs.
Spec: https://github.com/mandiant/OpenIOC_1.1
"""

import uuid
from datetime import datetime, timezone
from typing import Any
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom import minidom

from fastapi.responses import Response

from app.adapters.base import register_adapter
from app.adapters.query_filter import AdapterQueryFilter
from app.core.logging import get_logger

logger = get_logger(__name__)

# CTIR type → OpenIOC IndicatorItem Type / Context
_OPENIOC_TYPE_MAP: dict[str, tuple[str, str, str]] = {
    # ioc_type: (context_document, context_search, content_type)
    "ip":          ("Network",   "Network/DNS",         "string"),
    "domain":      ("Network",   "Network/DNS",         "string"),
    "url":         ("Network",   "Network/URI",         "string"),
    "hash_md5":    ("FileItem",  "FileItem/Md5sum",     "md5"),
    "hash_sha1":   ("FileItem",  "FileItem/Sha1sum",    "sha1"),
    "hash_sha256": ("FileItem",  "FileItem/Sha256sum",  "sha256"),
    "email":       ("Email",     "Email/From",          "string"),
    "filename":    ("FileItem",  "FileItem/FileName",   "string"),
    "other":       ("FileItem",  "FileItem/StringList/string", "string"),
}

_NS = "http://schemas.mandiant.com/2010/ioc"
_NS_XSI = "http://www.w3.org/2001/XMLSchema-instance"


def _ts(dt: datetime) -> str:
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%S")


def _prettify(element: Element) -> str:
    raw = tostring(element, encoding="unicode")
    return minidom.parseString(raw).toprettyxml(indent="  ")


def _build_indicator_item(parent: Element, ioc, type_name: str) -> None:
    ctx_doc, ctx_search, content_type = _OPENIOC_TYPE_MAP.get(
        type_name, ("FileItem", "FileItem/StringList/string", "string")
    )

    item = SubElement(
        parent,
        "IndicatorItem",
        attrib={
            "id": str(uuid.uuid5(uuid.NAMESPACE_URL, f"ctir:{type_name}:{ioc.ioc_value}")),
            "condition": "is",
            "preserve-case": "false",
            "negate": "false",
        },
    )
    ctx = SubElement(item, "Context")
    ctx.set("document", ctx_doc)
    ctx.set("search", ctx_search)
    ctx.set("type", "mir")

    content = SubElement(item, "Content", attrib={"type": content_type})
    content.text = ioc.ioc_value


class OpenIOCAdapter:
    name = "openioc"
    media_type = "application/xml"
    description = "OpenIOC 1.1 XML — IPA and legacy SIEM ingest"

    def serialize(
        self,
        iocs: list,
        meta: dict[str, Any],
        query_filter: AdapterQueryFilter,
    ) -> Response:
        type_map: dict[int, str] = meta.get("type_map", {})
        now = _ts(datetime.now(timezone.utc))

        # Root <ioc> element
        root = Element("ioc")
        root.set("id", str(uuid.uuid4()))
        root.set("last-modified", now)
        root.set("xmlns", _NS)
        root.set("xmlns:xsi", _NS_XSI)

        # Metadata
        short_desc = SubElement(root, "short_description")
        short_desc.text = "CTIR IOC Export"
        desc = SubElement(root, "description")
        desc.text = (
            f"Generated by CTIR at {now}. "
            f"Total: {meta.get('total', len(iocs))} IOCs."
        )
        authored_by = SubElement(root, "authored_by")
        authored_by.text = "CTIR"
        authored_date = SubElement(root, "authored_date")
        authored_date.text = now

        # Indicators wrapper
        indicators = SubElement(root, "definition")
        indicator_root = SubElement(
            indicators,
            "Indicator",
            attrib={
                "id": str(uuid.uuid4()),
                "operator": "OR",
            },
        )

        for ioc in iocs:
            type_name = type_map.get(ioc.ioc_type_id, "other")
            _build_indicator_item(indicator_root, ioc, type_name)

        xml_str = _prettify(root)
        logger.info("openioc_serialized", ioc_count=len(iocs))
        return Response(
            content=xml_str,
            media_type="application/xml",
            headers={"X-CTIR-Format": "openioc-1.1"},
        )


register_adapter(OpenIOCAdapter())